name: Keep HF Space Awake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping HF Space
        run: curl -L --max-time 120 -s -o /dev/null -w "%{http_code}\n" https://onemorehero-my-n8n-app.hf.space
